//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlchemyElement
    {
        public AlchemyElement()
        {
            this.AlchemyCards = new HashSet<AlchemyCard>();
            this.AlchemyCosts = new HashSet<AlchemyCost>();
            this.AlchemyCosts1 = new HashSet<AlchemyCost>();
            this.AlchemyCosts2 = new HashSet<AlchemyCost>();
            this.AlchemyCosts3 = new HashSet<AlchemyCost>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Initial { get; set; }
        public string StrokeColor { get; set; }
        public string FillColor { get; set; }
    
        public virtual ICollection<AlchemyCard> AlchemyCards { get; set; }
        public virtual ICollection<AlchemyCost> AlchemyCosts { get; set; }
        public virtual ICollection<AlchemyCost> AlchemyCosts1 { get; set; }
        public virtual ICollection<AlchemyCost> AlchemyCosts2 { get; set; }
        public virtual ICollection<AlchemyCost> AlchemyCosts3 { get; set; }
    }
}
