//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlchemyCard
    {
        public AlchemyCard()
        {
            this.AlchemyCosts = new HashSet<AlchemyCost>();
            this.Decks = new HashSet<Deck>();
            this.AlchemyGoals = new HashSet<AlchemyGoal>();
        }
    
        public int Id { get; set; }
        public int Element { get; set; }
        public string Name { get; set; }
        public Nullable<int> VictoryPoints { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual AlchemyElement AlchemyElement { get; set; }
        public virtual AlchemyRank AlchemyRank { get; set; }
        public virtual ICollection<AlchemyCost> AlchemyCosts { get; set; }
        public virtual ICollection<Deck> Decks { get; set; }
        public virtual ICollection<AlchemyGoal> AlchemyGoals { get; set; }
    }
}
