//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlchemyCost
    {
        public int Id { get; set; }
        public int CardId { get; set; }
        public int Order { get; set; }
        public Nullable<int> ElementA { get; set; }
        public Nullable<int> ElementB { get; set; }
        public Nullable<int> ElementC { get; set; }
        public Nullable<int> ElementD { get; set; }
    
        public virtual AlchemyCard AlchemyCard { get; set; }
        public virtual AlchemyElement AlchemyElement { get; set; }
        public virtual AlchemyElement AlchemyElement1 { get; set; }
        public virtual AlchemyElement AlchemyElement2 { get; set; }
        public virtual AlchemyElement AlchemyElement3 { get; set; }
    }
}
