//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CardDesignEntities : DbContext
    {
        public CardDesignEntities()
            : base("name=CardDesignEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlchemyCard> AlchemyCards { get; set; }
        public virtual DbSet<AlchemyCost> AlchemyCosts { get; set; }
        public virtual DbSet<AlchemyElement> AlchemyElements { get; set; }
        public virtual DbSet<AlchemyRank> AlchemyRanks { get; set; }
        public virtual DbSet<Deck> Decks { get; set; }
        public virtual DbSet<AlchemyGoal> AlchemyGoals { get; set; }
    }
}
