//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deck
    {
        public Deck()
        {
            this.AlchemyCards = new HashSet<AlchemyCard>();
            this.AlchemyGoals = new HashSet<AlchemyGoal>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<AlchemyCard> AlchemyCards { get; set; }
        public virtual ICollection<AlchemyGoal> AlchemyGoals { get; set; }
    }
}
